package com.codefresh.api.models;

public class BuildResponse {

    private String request;
    private String trigger;
    private String triggeredBy;
    private boolean webhookTriggered;
    private String triggerType;
    private String[] terminationRequest;
    private String[] systemEvents;
    private String finalWorkflowYaml;
    private Variable exportedVariables;
    private String[] pendingApprovals;
    private boolean useDebugger;
    private String initiator;
    private String initiatorAvatar;
    private boolean hasImplicitGitCloneStep;
    private String packId;
    private String userYamlDescriptor;
    private String[] steps;
    private String progress_id;
    private String _id;
    private String account;
    private boolean autoGeneratedYaml;
    private String buildType;
    private String created;
    private String project;
    private String projectId;
    private String serviceId;
    private String serviceName;
    private String pipelineName;
    private int triggersCount;
    private String repoOwner;
    private String repoName;
    private String id;
    private String finished;
    private String started;
    private int delayed;
    private String status;
    private boolean pendingLicense;
    private String progress;

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public boolean isAutoGeneratedYaml() {
        return autoGeneratedYaml;
    }

    public void setAutoGeneratedYaml(boolean autoGeneratedYaml) {
        this.autoGeneratedYaml = autoGeneratedYaml;
    }

    public String getBuildType() {
        return buildType;
    }

    public void setBuildType(String buildType) {
        this.buildType = buildType;
    }

    public String getCreated() {
        return created;
    }

    public void setCreated(String created) {
        this.created = created;
    }

    public String getProject() {
        return project;
    }

    public void setProject(String project) {
        this.project = project;
    }

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public String getServiceId() {
        return serviceId;
    }

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    public String getServiceName() {
        return serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    public String getPipelineName() {
        return pipelineName;
    }

    public void setPipelineName(String pipelineName) {
        this.pipelineName = pipelineName;
    }

    public int getTriggersCount() {
        return triggersCount;
    }

    public void setTriggersCount(int triggersCount) {
        this.triggersCount = triggersCount;
    }

    public String getRepoOwner() {
        return repoOwner;
    }

    public void setRepoOwner(String repoOwner) {
        this.repoOwner = repoOwner;
    }

    public String getRepoName() {
        return repoName;
    }

    public void setRepoName(String repoName) {
        this.repoName = repoName;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFinished() {
        return finished;
    }

    public void setFinished(String finished) {
        this.finished = finished;
    }

    public String getStarted() {
        return started;
    }

    public void setStarted(String started) {
        this.started = started;
    }

    public int getDelayed() {
        return delayed;
    }

    public void setDelayed(int delayed) {
        this.delayed = delayed;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public boolean isPendingLicense() {
        return pendingLicense;
    }

    public void setPendingLicense(boolean pendingLicense) {
        this.pendingLicense = pendingLicense;
    }

    public String getProgress() {
        return progress;
    }

    public void setProgress(String progress) {
        this.progress = progress;
    }

    public String getTrigger() {
        return trigger;
    }

    public void setTrigger(String trigger) {
        this.trigger = trigger;
    }

    public String getTriggeredBy() {
        return triggeredBy;
    }

    public void setTriggeredBy(String triggeredBy) {
        this.triggeredBy = triggeredBy;
    }

    public boolean isWebhookTriggered() {
        return webhookTriggered;
    }

    public void setWebhookTriggered(boolean webhookTriggered) {
        this.webhookTriggered = webhookTriggered;
    }

    public String getTriggerType() {
        return triggerType;
    }

    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType;
    }

    public String[] getTerminationRequest() {
        return terminationRequest;
    }

    public void setTerminationRequest(String[] terminationRequest) {
        this.terminationRequest = terminationRequest;
    }

    public String[] getSystemEvents() {
        return systemEvents;
    }

    public void setSystemEvents(String[] systemEvents) {
        this.systemEvents = systemEvents;
    }

    public String getFinalWorkflowYaml() {
        return finalWorkflowYaml;
    }

    public void setFinalWorkflowYaml(String finalWorkflowYaml) {
        this.finalWorkflowYaml = finalWorkflowYaml;
    }

    public Variable getExportedVariables() {
        return exportedVariables;
    }

    public void setExportedVariables(Variable exportedVariables) {
        this.exportedVariables = exportedVariables;
    }

    public String[] getPendingApprovals() {
        return pendingApprovals;
    }

    public void setPendingApprovals(String[] pendingApprovals) {
        this.pendingApprovals = pendingApprovals;
    }

    public boolean isUseDebugger() {
        return useDebugger;
    }

    public void setUseDebugger(boolean useDebugger) {
        this.useDebugger = useDebugger;
    }

    public String getInitiator() {
        return initiator;
    }

    public void setInitiator(String initiator) {
        this.initiator = initiator;
    }

    public String getInitiatorAvatar() {
        return initiatorAvatar;
    }

    public void setInitiatorAvatar(String initiatorAvatar) {
        this.initiatorAvatar = initiatorAvatar;
    }

    public boolean isHasImplicitGitCloneStep() {
        return hasImplicitGitCloneStep;
    }

    public void setHasImplicitGitCloneStep(boolean hasImplicitGitCloneStep) {
        this.hasImplicitGitCloneStep = hasImplicitGitCloneStep;
    }

    public String getPackId() {
        return packId;
    }

    public void setPackId(String packId) {
        this.packId = packId;
    }

    public String getUserYamlDescriptor() {
        return userYamlDescriptor;
    }

    public void setUserYamlDescriptor(String userYamlDescriptor) {
        this.userYamlDescriptor = userYamlDescriptor;
    }

    public String[] getSteps() {
        return steps;
    }

    public void setSteps(String[] steps) {
        this.steps = steps;
    }

    public String getProgress_id() {
        return progress_id;
    }

    public void setProgress_id(String progress_id) {
        this.progress_id = progress_id;
    }

    public String get_id() {
        return _id;
    }

    public void set_id(String _id) {
        this._id = _id;
    }

    public String getRequest() {
        return request;
    }

    public void setRequest(String request) {
        this.request = request;
    }
}
